"""create conflicts table

Revision ID: 6c7de7589cb8
Revises: a9d02a05ba07
Create Date: 2026-07-11 21:53:20.683266

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6c7de7589cb8"
down_revision: Union[str, Sequence[str], None] = "a9d02a05ba07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conflicts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("investigation_id", sa.String(), nullable=False),
        sa.Column("branch_path", sa.String(), nullable=False),
        sa.Column("existing_result", sa.String(), nullable=False),
        sa.Column("incoming_result", sa.String(), nullable=False),
        sa.Column("incoming_notes", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("FLAGGED", "RESOLVED", name="conflict_status"),
            nullable=False,
        ),
        sa.Column(
            "resolution",
            sa.Enum("ACCEPT", "RESET", name="conflict_resolution"),
            nullable=True,
        ),
        sa.Column("resolved_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("conflicts")
    sa.Enum(name="conflict_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="conflict_resolution").drop(op.get_bind(), checkfirst=True)
