"""create investigations table

Revision ID: 8530eb789802
Revises: 6c7de7589cb8
Create Date: 2026-07-11 23:40:37.398399

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8530eb789802"
down_revision: Union[str, Sequence[str], None] = "6c7de7589cb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "investigations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE", "AWAITING_GEMBA", "COMPLETE", name="investigation_status"
            ),
            nullable=False,
        ),
        sa.Column("interrupt_type", sa.String(), nullable=True),
        sa.Column("current_depth", sa.Integer(), nullable=False),
        sa.Column("root_cause_found", sa.Boolean(), nullable=False),
        sa.Column("node_count", sa.Integer(), nullable=False),
        sa.Column("node_pending_count", sa.Integer(), nullable=False),
        sa.Column("awaiting_quorum", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_investigations_project_id"), "investigations", ["project_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_investigations_project_id"), table_name="investigations")
    op.drop_table("investigations")
    sa.Enum(name="investigation_status").drop(op.get_bind(), checkfirst=True)
