"""create audit_log table

Revision ID: a9d02a05ba07
Revises: 2ffe5e21da57
Create Date: 2026-07-11 15:07:39.433467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a9d02a05ba07"
down_revision: Union[str, Sequence[str], None] = "2ffe5e21da57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("investigation_id", sa.String(), nullable=False),
        sa.Column("driver_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "reset_type", sa.Enum("SOFT", "HARD", name="reset_type"), nullable=False
        ),
        sa.Column("branch_path", sa.String(), nullable=False),
        sa.Column("evidence_reference", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["driver_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table("audit_log")
    sa.Enum(name="reset_type").drop(op.get_bind(), checkfirst=True)
