"""create project_invitations table

Revision ID: da015062f102
Revises: a0b577f91e5b
Create Date: 2026-07-10 22:30:38.313551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "da015062f102"
down_revision: Union[str, Sequence[str], None] = "a0b577f91e5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_invitations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM(
                "OWNER",
                "ANALYST",
                "CONTRIBUTOR",
                "OPERATOR",
                "MANAGER",
                "VIEWER",
                name="project_member_role",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "EXPIRED", name="invitation_status"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_project_invitations_token"),
        "project_invitations",
        ["token"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_project_invitations_token"), table_name="project_invitations"
    )
    op.drop_table("project_invitations")
    op.execute("DROP TYPE IF EXISTS invitation_status")
    # ### end Alembic commands ###
