"""add description to projects

Revision ID: e73a90b6fcc9
Revises: 8530eb789802
Create Date: 2026-07-12 00:20:12.655847

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e73a90b6fcc9"
down_revision: Union[str, Sequence[str], None] = "8530eb789802"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("projects", "description")
    # ### end Alembic commands ###
