"""Brand assets must stay in sync with DESIGN.md tokens (US-30 T03).

The assets are generated by tools/generate_brand_assets.py; this test fails
if a token changed in DESIGN.md without regenerating, or an asset was
hand-edited away from the tokens.
"""

from pathlib import Path

import frontmatter
import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
BRAND = REPO_ROOT / "docs" / "brand"


def tokens() -> dict:
    return frontmatter.load(REPO_ROOT / "DESIGN.md").metadata["tokens"]


@pytest.mark.parametrize("mode", ["light", "dark"])
def test_node_status_sheet_uses_current_tokens(mode):
    svg = (BRAND / f"node-status-{mode}.svg").read_text().lower()
    t = tokens()
    for name in ("active", "ruledOut", "rootCause", "suspended", "conflict"):
        assert t["nodeStatus"][name][mode].lower() in svg, (
            f"node-status-{mode}.svg missing nodeStatus.{name} — regenerate via tools/generate_brand_assets.py"
        )


@pytest.mark.parametrize("mode", ["light", "dark"])
def test_logo_uses_blue_chrome_and_coral_node(mode):
    svg = (BRAND / f"logo-{mode}.svg").read_text().lower()
    t = tokens()
    assert t["colors"]["accent"][mode].lower() in svg, "logo ring must be chrome blue"
    assert t["nodeStatus"]["active"][mode].lower() in svg, "logo cause-node must be coral"


@pytest.mark.parametrize("mode", ["light", "dark"])
def test_all_four_assets_exist(mode):
    assert (BRAND / f"node-status-{mode}.svg").exists()
    assert (BRAND / f"logo-{mode}.svg").exists()
